In [16]:
'''
Numpy (Numerical Python) là thư viện hỗ trợ:
  - Làm việc với mảng nhiều chiểu.
  - Các phép toán ma trận và đại số tuyến tính.
  - Tối ưu hóa hiệu suất tính toán nhanh hơn nhiều so với list thông thường trong Python.
'''
# Cài đặt Numpy:  pip install numpy

# IMPORT THƯ VIỆN
import numpy as np

# TẠO MẢNG NUMPY
a = np.array([1, 2, 3]) #mảng 1 chiểu
b = np.array([[1, 2], [3, 4]])  #mảng 2 chiểu

# KIỂM TRA THÔNG TIN MẢNG
print("Kích thước mảng: ", a.shape)
print("Kiểu dữ liệu: ", a.dtype)
print("Số chiều: ", b.ndim)
print("Số phần tử: ", b.size)

# TẠO MẢNG ĐẶC BIỆT
print("Mảng toàn số 0: \n", np.zeros((2, 3)))
print("Mảng toàn số 1: \n", np.ones((3, 3)))
print("Ma trận đơn vị: \n", np.eye(3))
print("Mảng cách đều nhau: ", np.arange(0, 10, 2))  # [0 2 4 6 8]
print("Tạo mảng với số phần tử đều nhau từ đầu->cuối: ", np.linspace(0, 1, 5)) # [0.   0.25 0.5  0.75 1.]



Kích thước mảng:  (3,)
Kiểu dữ liệu:  int64
Số chiều:  2
Số phần tử:  4
Mảng toàn số 0: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Mảng toàn số 1: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Ma trận đơn vị: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mảng cách đều nhau:  [0 2 4 6 8]
Tạo mảng với số phần tử đều nhau từ đầu->cuối:  [0.   0.25 0.5  0.75 1.  ]


In [17]:
# CÁC PHÉP TOÁN
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Tổng 2 mảng: ", x + y)
print("Hiệu 2 mảng: ", x - y)
print("Tích 2 mảng: ", x * y)
print("Thương 2 mảng: ", x / y)
print("Phép lũy thừa: ", x ** y)
print("Phép chia lấy phần dư: ", x % y)
print("Phép tích vô hướng: ", x.dot(y)) # Tích vô hướng = 1*4 + 2*5 + 3*6 = 32

# TRUY CẬP MẢNG & CẮT MẢNG
t = np.array([[1, 2, 3],
              [4, 5, 6]]
            )
#dòng 0: [1, 2, 3]
# dòng 1: [4, 5, 6]

print(t[0, 1])  # lấy dòng 0, cột 1
print(t[:, 1])  # lấy tất cả dòng, nhưng chỉ cột 1 [2, 5]
print(t[1, :])  # Lấy dòng 1, tất cả cột [4 5 6]
print(t[1, ...]) # Lấy tất cả mọi thứ còn lại sau khi chọn trục đầu tiên = 1



Tổng 2 mảng:  [5 7 9]
Hiệu 2 mảng:  [-3 -3 -3]
Tích 2 mảng:  [ 4 10 18]
Thương 2 mảng:  [0.25 0.4  0.5 ]
Phép lũy thừa:  [  1  32 729]
Phép chia lấy phần dư:  [1 2 3]
Phép tích vô hướng:  32
2
[2 5]
[4 5 6]
[4 5 6]
